package com.booking.system.enums;

public enum NotificationType {
    BOOKING_CREATED,
    BOOKING_PENDING_APPROVAL,
    BOOKING_APPROVED,
    BOOKING_REJECTED,
    BOOKING_CANCELLED,
    BOOKING_UPDATED,
    BOOKING_REMINDER,
    ROOM_CHANGED,
    VEHICLE_CHANGED,
    PROFILE_UPDATE_REQUESTED,
    PROFILE_UPDATE_APPROVED,
    PROFILE_UPDATE_REJECTED,
    ACCOUNT_REGISTRATION_PENDING,
    ACCOUNT_REGISTRATION_REQUESTED,
    ACCOUNT_REGISTRATION_APPROVED,
    ACCOUNT_REGISTRATION_REJECTED,
    SYSTEM
}
