CREATE TABLE hr_payroll_imports (
    id VARCHAR(36) NOT NULL,
    source_file_name VARCHAR(255) NOT NULL,
    file_sha256 VARCHAR(64) NOT NULL,
    file_size BIGINT NOT NULL,
    source_sheet_name VARCHAR(100) NOT NULL,
    payroll_month VARCHAR(7) NOT NULL,
    status VARCHAR(32) NOT NULL,
    total_rows INT NOT NULL DEFAULT 0,
    valid_rows INT NOT NULL DEFAULT 0,
    ready_rows INT NOT NULL DEFAULT 0,
    skipped_rows INT NOT NULL DEFAULT 0,
    invalid_rows INT NOT NULL DEFAULT 0,
    last_error VARCHAR(1000) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_by_actor VARCHAR(320) NOT NULL,
    updated_by_actor VARCHAR(320) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_hr_payroll_imports PRIMARY KEY (id),
    CONSTRAINT uk_hr_payroll_import_sha UNIQUE (file_sha256),
    INDEX idx_hr_payroll_import_status_created (status, created_at)
);

CREATE TABLE hr_payroll_import_rows (
    id VARCHAR(36) NOT NULL,
    import_id VARCHAR(36) NOT NULL,
    source_row_number INT NOT NULL,
    employee_id VARCHAR(36) NULL,
    employee_code VARCHAR(32) NOT NULL,
    employee_name VARCHAR(255) NOT NULL,
    payload_json JSON NOT NULL,
    status VARCHAR(32) NOT NULL,
    telegram_chat_id BIGINT NULL,
    telegram_user_id BIGINT NULL,
    error_message VARCHAR(1000) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_by_actor VARCHAR(320) NOT NULL,
    updated_by_actor VARCHAR(320) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_hr_payroll_import_rows PRIMARY KEY (id),
    CONSTRAINT uk_hr_payroll_import_employee UNIQUE (import_id, employee_code),
    CONSTRAINT fk_hr_payroll_row_import FOREIGN KEY (import_id) REFERENCES hr_payroll_imports(id) ON DELETE CASCADE,
    CONSTRAINT fk_hr_payroll_row_employee FOREIGN KEY (employee_id) REFERENCES hr_employees(id) ON DELETE RESTRICT,
    INDEX idx_hr_payroll_row_import_status (import_id, status, source_row_number),
    INDEX idx_hr_payroll_row_employee_code (employee_code)
);

CREATE TABLE hr_payroll_campaigns (
    id VARCHAR(36) NOT NULL,
    import_id VARCHAR(36) NOT NULL,
    status VARCHAR(32) NOT NULL,
    delivery_mode VARCHAR(16) NOT NULL DEFAULT 'TEXT',
    batch_size INT NOT NULL DEFAULT 50,
    total_count INT NOT NULL DEFAULT 0,
    pending_count INT NOT NULL DEFAULT 0,
    sending_count INT NOT NULL DEFAULT 0,
    sent_count INT NOT NULL DEFAULT 0,
    retry_count INT NOT NULL DEFAULT 0,
    failed_count INT NOT NULL DEFAULT 0,
    skipped_count INT NOT NULL DEFAULT 0,
    started_at DATETIME(6) NULL,
    finished_at DATETIME(6) NULL,
    last_error VARCHAR(1000) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_by_actor VARCHAR(320) NOT NULL,
    updated_by_actor VARCHAR(320) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_hr_payroll_campaigns PRIMARY KEY (id),
    CONSTRAINT uk_hr_payroll_campaign_import UNIQUE (import_id),
    CONSTRAINT fk_hr_payroll_campaign_import FOREIGN KEY (import_id) REFERENCES hr_payroll_imports(id) ON DELETE RESTRICT,
    INDEX idx_hr_payroll_campaign_status (status, created_at)
);

CREATE TABLE hr_payroll_deliveries (
    id VARCHAR(36) NOT NULL,
    campaign_id VARCHAR(36) NOT NULL,
    import_row_id VARCHAR(36) NOT NULL,
    employee_id VARCHAR(36) NULL,
    employee_code VARCHAR(32) NOT NULL,
    employee_name VARCHAR(255) NOT NULL,
    telegram_chat_id BIGINT NULL,
    status VARCHAR(32) NOT NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    last_error VARCHAR(1000) NULL,
    sent_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_by_actor VARCHAR(320) NOT NULL,
    updated_by_actor VARCHAR(320) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_hr_payroll_deliveries PRIMARY KEY (id),
    CONSTRAINT uk_hr_payroll_delivery_row UNIQUE (campaign_id, import_row_id),
    CONSTRAINT fk_hr_payroll_delivery_campaign FOREIGN KEY (campaign_id) REFERENCES hr_payroll_campaigns(id) ON DELETE CASCADE,
    CONSTRAINT fk_hr_payroll_delivery_row FOREIGN KEY (import_row_id) REFERENCES hr_payroll_import_rows(id) ON DELETE RESTRICT,
    INDEX idx_hr_payroll_delivery_status (campaign_id, status, updated_at),
    INDEX idx_hr_payroll_delivery_employee (employee_code)
);
