CREATE TABLE hr_attendance_imports (
    id VARCHAR(36) NOT NULL,
    source_file_name VARCHAR(255) NOT NULL,
    file_sha256 VARCHAR(64) NOT NULL,
    file_size BIGINT NOT NULL,
    source_sheet_name VARCHAR(100) NOT NULL,
    attendance_month VARCHAR(7) NULL,
    header_row INT NOT NULL,
    configuration_json JSON NOT NULL,
    status VARCHAR(32) NOT NULL,
    total_rows INT NOT NULL DEFAULT 0,
    valid_rows INT NOT NULL DEFAULT 0,
    error_rows INT NOT NULL DEFAULT 0,
    last_error VARCHAR(1000) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_by_actor VARCHAR(320) NOT NULL,
    updated_by_actor VARCHAR(320) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_hr_attendance_imports PRIMARY KEY (id),
    CONSTRAINT uk_hr_attendance_import_sha UNIQUE (file_sha256),
    INDEX idx_hr_attendance_import_created (created_at)
);

CREATE TABLE hr_attendance_records (
    id VARCHAR(36) NOT NULL,
    import_id VARCHAR(36) NOT NULL,
    employee_id VARCHAR(36) NULL,
    employee_code VARCHAR(32) NOT NULL,
    employee_name VARCHAR(255) NULL,
    work_date DATE NULL,
    punches_json JSON NULL,
    check_in TIME NULL,
    check_out TIME NULL,
    work_value DECIMAL(4,2) NOT NULL DEFAULT 0,
    late_minutes INT NOT NULL DEFAULT 0,
    early_minutes INT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL,
    source_row_number INT NOT NULL,
    error_message VARCHAR(1000) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_by_actor VARCHAR(320) NOT NULL,
    updated_by_actor VARCHAR(320) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_hr_attendance_records PRIMARY KEY (id),
    CONSTRAINT fk_hr_attendance_record_import FOREIGN KEY (import_id) REFERENCES hr_attendance_imports(id) ON DELETE CASCADE,
    CONSTRAINT fk_hr_attendance_record_employee FOREIGN KEY (employee_id) REFERENCES hr_employees(id) ON DELETE RESTRICT,
    CONSTRAINT uk_hr_attendance_record_source UNIQUE (import_id, source_row_number),
    INDEX idx_hr_attendance_record_import (import_id, source_row_number),
    INDEX idx_hr_attendance_record_employee_date (employee_code, work_date)
);

INSERT INTO hr_system_settings (setting_key, setting_value, category, description, created_by_actor, updated_by_actor)
VALUES
('attendance.headerRow', '2', 'ATTENDANCE', 'Dòng tiêu đề Excel (đánh số từ 1)', 'system', 'system'),
('attendance.employeeCodeColumn', 'B', 'ATTENDANCE', 'Cột mã nhân viên', 'system', 'system'),
('attendance.employeeNameColumn', 'C', 'ATTENDANCE', 'Cột họ tên', 'system', 'system'),
('attendance.dateColumn', 'E', 'ATTENDANCE', 'Cột ngày chấm công', 'system', 'system'),
('attendance.punchColumns', 'G,H,I,J', 'ATTENDANCE', 'Các cột giờ chấm công', 'system', 'system'),
('attendance.checkInStart', '04:00', 'ATTENDANCE', 'Bắt đầu khung Check in', 'system', 'system'),
('attendance.checkInEnd', '09:00', 'ATTENDANCE', 'Kết thúc khung Check in', 'system', 'system'),
('attendance.checkOutStart', '15:00', 'ATTENDANCE', 'Bắt đầu khung Check out', 'system', 'system'),
('attendance.checkOutEnd', '20:00', 'ATTENDANCE', 'Kết thúc khung Check out', 'system', 'system'),
('attendance.defaultCheckIn', '', 'ATTENDANCE', 'Giờ mặc định nếu thiếu Check in', 'system', 'system'),
('attendance.defaultCheckOut', '', 'ATTENDANCE', 'Giờ mặc định nếu thiếu Check out', 'system', 'system'),
('attendance.standardCheckIn', '07:30', 'ATTENDANCE', 'Giờ chuẩn tính đi trễ', 'system', 'system'),
('attendance.standardCheckOut', '16:30', 'ATTENDANCE', 'Giờ chuẩn tính về sớm', 'system', 'system'),
('attendance.graceMinutes', '10', 'ATTENDANCE', 'Số phút miễn trừ', 'system', 'system')
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value), category = VALUES(category), description = VALUES(description);
